### ISSUE TITLE
error with composer require virgil/sdk 

### ISSUE THREAD

**Issue by lorinczdev** [VirgilSecurity/virgil-sdk-php#22]
Hello,

when i'm trying to require virgil/sdk through composer i get this error:

Problem 1
    - Installation request for virgil/sdk ^5.0 -> satisfiable by virgil/sdk[v5.0.0].
    - virgil/sdk v5.0.0 requires virgil/crypto-api-implementation ^v5.0 -> no matching package found.

**Comment by PetrenkoAnton** [comment]
@lorinczdev , you need to install crypto before sdk:

composer require virgil/crypto virgil/sdk

**Comment by Rajat117** [comment]
I did that. I'm still getting the same error
 Problem 1
    - virgil/sdk v5.x-dev requires virgil/crypto-api-implementation ^v5.0 -> no matching package found.
    - virgil/sdk v5.1.0 requires virgil/crypto-api-implementation ^v5.0 -> no matching package found.
    - Installation request for virgil/sdk ^5.1 -> satisfiable by virgil/sdk[v5.1.0, v5.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

**Comment by danielyandev** [comment]
Why is this issue closed if  `composer require virgil/crypto virgil/sdk` is not a solution? I have `virgil/crypto 6.0` but I face the same issue when trying to install `virgil/sdk`
