### ISSUE TITLE
Can't seem to pull down composer package

### ISSUE THREAD

**Issue by bytewoopy** [VirgilSecurity/virgil-sdk-php#30]
Getting the following message when running **composer require virgil/sdk**:
----------------
`Using version ^5.1 for virgil/sdk
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - virgil/sdk v5.x-dev requires virgil/crypto-api-implementation ^v5.0 -> no matching package found.
    - virgil/sdk v5.1.0 requires virgil/crypto-api-implementation ^v5.0 -> no matching package found.
    - Installation request for virgil/sdk ^5.1 -> satisfiable by virgil/sdk[v5.1.0, v5.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
`

**Comment by bytewoopy** [comment]
Installing virgil/crypto then virgil/sdk also does not work, same error...

**Comment by lekoala** [comment]
you have to install virgil/crypto 5.1.1 for some reason, others don't work with latest releases

**Comment by lekoala** [comment]
but if you use virgil/crypto ^6.0 like I do now because I also use PureKit, then it's not possible to install the package. Maybe it will work once this is merged
https://github.com/VirgilSecurity/virgil-sdk-php/pull/29

**Comment by philipborbon** [comment]
Also experience this issue with composer.

@lekoala, Did you manage to install Virgil PHP SDK?

**Comment by philipborbon** [comment]
Got a successful composer install using this line
```
COMPOSER_MEMORY_LIMIT=-1 composer require virgil/crypto:5.1.1 virgil/sdk
```

**Comment by lekoala** [comment]
yes it works with virgil crypto 5.1.1 but not with the latest version

**Comment by Qzich** [comment]
close issue as it is not actual after v6 release
