### ISSUE TITLE
No support for PHP 8.1+

### ISSUE THREAD

**Issue by WouterWidgets** [VirgilSecurity/virgil-sdk-php#36]
On PHP 8.1, I get an error when running the `setup.sh` command:

```
./vendor/virgil/crypto-wrapper/_extensions/setup.sh -all -vendor
Сrypto extensions installation...
----------
Checking input... [OK]
Checking PHP version... [FAIL]
Error status: Invalid PHP version: 8.1
----------
Please try installing the extension manually in accordance with this instruction:
\e]8;;https://github.com/VirgilSecurity/virgil-cryptowrapper-php#additional-information\ahttps://github.com/VirgilSecurity/virgil-cryptowrapper-php#additional-information\e]8;;\a
----------
```

Manual installation does not seem to work either, as there are no files for PHP 8.1 in the extensions folder relevant for my OS:
https://github.com/VirgilSecurity/virgil-cryptowrapper-php/tree/master/_extensions/bin/linux_x86_64

Would it be possible to add support for PHP 8.1 and/or PHP 8.2?

Your help is much appreciated!

Regards, Wouter

**Comment by SergeySeroshtan** [comment]
Done in release https://github.com/VirgilSecurity/virgil-sdk-php/releases/tag/v6.4.0
